### ISSUE TITLE
How to contact you.

### ISSUE THREAD

**Issue by Myrninvollo** [pokemon-essentials/pokemon-essentials#1]
hi watching and been playing with this and MV-Online server. so far have the Dev branch running and just aboutt to convert most of the pokemon regions from my  old maps 16x16 maps in Tield to your 32 x 32 Tiled map using your map as a template. u can contact mmme via twitter - https://twitter.com/TherapyXgames  thanmk you for a brillent prodject and hope to help where i can.

**Comment by andarms** [comment]
You can find me in twitter as [@andarms](https://twitter.com/Andarms) or via discord with the same  username. I have a lot of idea for this projects any help is apreciated. If you see the dev  branch rigth now i add the pokemon characters and trainers in battle scene u can find the missing graphics assets used here https://drive.google.com/drive/folders/1oXbTrwAlL1SBVLykaHS1HlZf9c-IJWLo?usp=sharing

**Comment by Myrninvollo** [comment]
awesome :)
