### ISSUE TITLE
MV?

### ISSUE THREAD

**Issue by suryansh738** [pokemon-essentials/pokemon-essentials#2]
Are These For MV OR For Vx OR XP

**Comment by andarms** [comment]
yes MV, but there is still a lot of work to do, I have several great ideas, but now I do not have much time to invest in this project. In a few weeks I hope to continue. 

if u wanna try, download the develop brach and the aditional assets from the link in the readme.

**Comment by suryansh738** [comment]
Can you please make a video on installing them as I am having some problems
installing
