### ISSUE TITLE
Working together?

### ISSUE THREAD

**Issue by c0derMo** [pokemon-essentials/pokemon-essentials#3]
Hey there,
firstly, sorry for using an issue for this, but it's the only way of contacting you which I found. I'm c0derMo, one of the programmers of MonsterMaker, another project of making an Pokemon Engine for RPG Maker MV. You can learn more about our project here: https://forums.rpgmakerweb.com/index.php?threads/monster-maker-pocket-monster-edition-all-positions-open.85901/
Since we are always looking for new people and ways, to make our progress faster, one of our discord-members posted your Repo, and we decided it would be great if we are working together. It could really speed up our progress.
If you want to work with us, or still have some questions open, feel free to email me at c0derMo@curryato.de or simply reply to this issue.

**Comment by andarms** [comment]
Sure, please comment here your discord server to join in and maybe someone else will find the link and join as well, while i figure out how to make a proper communication channel to this project.

Right now i a little busy but i didn't drop the project.

**Comment by c0derMo** [comment]
https://discord.gg/x8cTzgU

Our project manager will talk to you there ^^
